default: &default
  key_path: /Users/mobitar/Desktop/standard-notes/dev/extensions-server/.ssh/namewhale.pem
  repo_url: https://github.com/standardnotes/extensions-server.git
  user: ec2-user

staging:
  <<: *default
  server: staging.extensions.standardnotes.org
  branch: staging
  deploy_to: ~/staging-extensions-server

production:
  <<: *default
  server: extensions.standardnotes.org
  deploy_to: ~/extensions-server
