# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f7353d0601ffd1675aa642390def1cd8fc7dc0dde58fbc1f3c18a55c7767cdab01a361fe1230079f3af20333d04b4d1778ba31c7b7b81e875bf220dde5799c9

test:
  secret_key_base: b560960ae0d0f3b023bc44e79bc8ff012ceb0c979ffbfd19dc3fa1055f58e23fa822a9fab4cd5261829159fd0b6c6d6ded45627ca8e1013540145ddbb70169e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
